apiVersion: v1
kind: Service
metadata:
  name: janua-website
  namespace: janua
  labels:
    app: janua-website
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4104
      protocol: TCP
      name: http
  selector:
    app: janua-website
