apiVersion: v1
kind: Service
metadata:
  name: janua-docs
  namespace: janua
  labels:
    app: janua-docs
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4103
      protocol: TCP
      name: http
  selector:
    app: janua-docs
