apiVersion: v1
kind: Service
metadata:
  name: janua-admin
  namespace: janua
  labels:
    app: janua-admin
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4102
      protocol: TCP
      name: http
  selector:
    app: janua-admin
